export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(common-aliases docker docker-compose git git-flow gradle jira kubectl mvn pip web-search)
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${HOME}/bin:${HOME}/.local/bin"
source $ZSH/oh-my-zsh.sh

function gfp() {
    for i in `git remote`; do
        git fetch --prune $i
    done
}

function gco() {
    git checkout
}

function gpod() {
    git pull origin develop
}

function grprt() {
    lsof -i :$1 -S
}

function gitCurrentBranch() {
    git rev-parse --abbrev-ref HEAD
}

function gitGraph() {
    git log --graph --oneline --all
}

function gitDummyCommit() {
    git commit --allow-empty -m ${1}
}

function gitDeleteRemote() {
    git push -d origin ${1}
}

function gitDeleteLocal() {
    git branch -d ${1}
}

function gitDeleteUntracked() {
    git fetch -p && for branch in $(git for-each-ref --format '%(refname) %(upstream:track)' refs/heads | awk '$2 == "[gone]" {sub("refs/heads/", "", $1); print $1}'); do git branch -D $branch; done
}

function migrateGitRepo() {
    if [ -z $1 ]; then
        echo "Please provide the new git repo URL"
        return
    fi

    for remote in `git branch -r | grep -v master `; do
        git checkout --track $remote
    done

    git remote rm origin
    git remote add origin $1
    git remote show origin
    git push origin '*:*'
}

if [ -f $HOME/.zshrc.custom ]; then
    source $HOME/.zshrc.custom
fi
